datadog:
  site: datadoghq.com
  apiKeyExistingSecret: datadog-secret
  clusterName: datadog-week

  tags:
    - app:ecommerce
    - project:datadog-week
    - team:sre
    - env:prd

  logs:
    enabled: true
    containerCollectAll: true

  apm:
    enabled: true
    portEnabled: true

  processAgent:
    enabled: true
    processCollection: true

  kubelet:
    tlsVerify: false

agents:
  containers:
    agent:
      resources: {}
    traceAgent:
      resources: {}

clusterAgent:
  enabled: true
  createPodDisruptionBudget: true